### ISSUE TITLE
大佬你好.很好的项目.我有点想法你看看合适吗

### ISSUE THREAD

**Issue by qihuoren** [Ifan24/GPT_subtitles#1]
这个项目还需要下载whisper 需要很大的内容.而且对机器也有要求.比较麻烦
1,能否直接调用whisper api进行转录.这样更便捷.(whisper api对大小有限制.可以设置分割之后在合并https:www.youtube.com/watch?v=-FtsoKryhPY )这个视频它是把超过25M大小的视频进行了分割成24M,之后在合并再对齐分割后造成的时间轴不对齐问题
2.直接目前调用chat gpt api进行翻译.会有问题.比如上下文.比如翻译更糟糕之类的这个可以调用 deepl api 会比谷歌更好.
3. 你里面提到了 webGUI 要用小模型.(其实用第一条的whisper api 直接是最大模型.)

**Comment by Ifan24** [comment]
> 1,能否直接调用whisper api进行转录.这样更便捷.(whisper api对大小有限制.可以设置分割之后在合并https:www.youtube.com/watch?v=-FtsoKryhPY )这个视频它是把超过25M大小的视频进行了分割成24M,之后在合并再对齐分割后造成的时间轴不对齐问题

我还没有用过whisper的api，但如果硬件和网络是个问题的话，感觉用colab来跑应该还不错，跑完之后再下载字幕文件就好了，我之后再完善一下colab的例子吧。关于whisper的api用最大模型的问题，我在本地跑的时候发现并不是越大的模型效果就越好，有时候large-2会有幻觉的问题（hallucination ），这时候用medium跑可能就没关系，如果api不能选用什么模型那问题还蛮大的。

> 2.直接目前调用chat gpt api进行翻译.会有问题.比如上下文.比如翻译更糟糕之类的这个可以调用 deepl api 会比谷歌更好.

翻译上下文的问题源头来自于whisper分割句子时会把一句话英文分成到两句，可能是因为句子过长或者句子结构过于复杂，这个我看到很多issue，但都没有很好的解决方法，我参考了一个思路是先分成word-level segment，然后在自己把每段话拼起来，这个方法并不是完美的但是还是让翻译变得容易了不少。
关于deepL的api，因为需要注册一个api的key，所以我没弄。但我现在已经完全放弃机器翻译了，用大语言模型来翻译质量真的高了很多，不仅能联系上下文还可以给一些额外的信息来更准确的翻译，名词的翻译也更好

> 3. 你里面提到了 webGUI 要用小模型.(其实用第一条的whisper api 直接是最大模型.)

webGUI这个指的是使用像[stable-vicuna-13b-delta](https://huggingface.co/CarperAI/stable-vicuna-13b-delta)这样的可以个人用的语言模型，我试的几个都不是用中文专门fine-tune的，所以效果都很差，甚至还不如传统的机器翻译，如果以后找到一个专门fine-tune中英翻译的模型，效果还不错的话可以整合进来，这样就不需要花钱用openai的api了

**Comment by qihuoren** [comment]
不好意思 对不起 ,可能是我表达的不够清楚.whisper api 可以选择你需要使用的模型.它可能是最新的模型. 我想他是收费的可能各方面效果可能会好一些.可能处理起来比用colab要简单.我想表达的是.这样能减轻工作量.加快开发速度. (这些api使用不贵.淘宝很多免费账号卖的不贵.作为个人使用基本满足)

deepl确实自然度上不如gpt好.它也是增加了ai大语言模型训练,相比gpt差很多.我也是希望能用pgt实现更好.在gitbub还没发现能处理好翻译准确度的问题.     成字词级句段，然后在自己把每段话拼起来 不知道效果如何 很期待.
