### ISSUE TITLE
不能使用了吗?

### ISSUE THREAD

**Issue by peaceful610** [Ifan24/GPT_subtitles#7]
使用 pip install -r requirements.txt 命令安装所需的依赖项失败。
无法为sentencepiece构建轮子（wheel）:

这个错误发生在尝试编译sentencepiece这个Python库时。错误信息中提到了无法打开一个叫做“sentencepiece_processor.h”的文件。这通常意味着在构建过程中缺少了必要的头文件或依赖。
另外，还出现了一个编译器警告，关于/MD和/MT选项的冲突。这表明在编译设置中可能存在一些不一致。
无法从GitHub克隆openai/whisper:

这个错误是在尝试从GitHub克隆whisper库时发生的。错误信息“fatal: unable to access 'https://github.com/openai/whisper.git/': Failure when receiving data from the peer”表明在网络连接过程中出现了问题。这可能是由于网络问题、GitHub服务器问题或者安全设置（如防火墙）阻止了访问。

**Comment by Ifan24** [comment]
感谢你提供的错误信息，关于sentencepiece的安装问题，能否麻烦提供一下完整的错误日志？

> 错误信息“fatal: unable to access 'https://github.com/openai/whisper.git/': Failure when receiving data from the peer”

至于无法从GitHub克隆whisper库的问题，我自己尝试在Google Colab上安装和使用，似乎没有遇到任何问题。如果方便的话，可以尝试下连接VPN来安装依赖项，可能是因为墙的原因部分依赖项的库没有被安装
