### ISSUE TITLE
no English translation on Whisper 

### ISSUE THREAD

**Issue by fahd200581** [Ifan24/GPT_subtitles#8]
for some reason the code only translate to zh even if you change the parameter to en, I used to be able to translate to english but not anymore

**Comment by Ifan24** [comment]
Hi, I'm trying to reproduce this issue. Could you share the parameters you used when you ran the script?

**Comment by fahd200581** [comment]
I'm using the colab notebook, when I change the target language to en it still translate to zh

**Comment by fahd200581** [comment]
#@title Running the Script

#@markdown If `video_path` is a YouTube link, the video will be downloaded at the `video`.
video_path = 'https://www.youtube.com/watch?v=F91vq9Clekk&pp=ygUVZmFsc2Vwb3NpdGl2ZSBwb2RjYXN0' #@param {type: 'string'}

#@markdown Choose a Whisper model.
model_type = 'large'  #@param ["base", "small", "medium", "large"]

#@markdown The language to translate to (use language code).
target_language = 'en' #@param {type: 'string'}

#@markdown Method to use for translation.
translation_method = 'whisper' #@param ["google", "gpt", "whisper", "m2m100"]

if 'www.youtube.com' in video_path:
  !python /content/youtube_dual_subtitles/main.py --youtube_url {video_path} --model {model_type} --target_language {target_language} --translation_method {translation_method}
else:
  !python /content/youtube_dual_subtitles/main.py --local_video {video_path} --model {model_type} --target_language {target_language} --translation_method {translation_method}

**Comment by Ifan24** [comment]
Hi, I just pushed a change that should fix the issue with translating to English using Whisper. It should now set the task as "translate" when the target language is English, as specified in the Whisper documentation. Please try running the script again with your desired target language and let me know if you encounter any further issues. Thanks for reporting this bug!

**Comment by fahd200581** [comment]
thank you so much it works lika a charm! 
I think even better than before, now it translate directly, before it used to provide the transcription then it translates it. now it's much faster.

I also had an Idea, I'm not sure if possible to use groqcloud and LLAMA 3 in this project for translation, as GroqCloud provides free API, that would be dope 

thanks again for your fast response, such a great project

**Comment by Ifan24** [comment]
Thanks for liking the project!

I've experimented with LLAMA 3 and other open-source LLMs for translation, but they often struggle with non-English output, likely due to their smaller model size. Fine-tuning could help, but it's resource-intensive and only works for that specific language. For now, those larger LLMs remain the most reliable choice, but I'm always open to exploring new possibilities as language models advance.

I appreciate your input for improving the project!
